version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
#      - db-data:/var/lib/mysql
    networks:
      - internal

  elasticsearch:
    image: elasticsearch:2.4.1
    ports:
     - "9200:9200"
    container_name: elasticsearch
    command: elasticsearch -Des.node.name="Elasticsearch_Connector"
    networks:
      - internal

  varnish:
    image: wodby/drupal-varnish
    container_name: varnish
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 80
      VARNISH_MEMORY_SIZE: 256M
      VARNISH_STORAGE_SIZE: 1024M
    ports:
      - "8081:6081" # HTTP Proxy
      - "8082:6082" # Control terminal
    networks:
      - internal

  iip_server:
    build:
      context: ./iip_image
      dockerfile: Dockerfile
    container_name: iip_image
    ports:
      - "8080:80"
    volumes:
      - ./iip_image/images:/images
    networks:
      - internal

  drupal:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: drupal
    ports:
      - "80:80"
    depends_on:
      - mysql
      - varnish
      - elasticsearch
      - iip_server
    restart: unless-stopped
    volumes:
      - ./iip_image/data:/var/www/html/drupal/sites/default/files
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  drupal-data:
# db-data:
