version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
#      - db-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    build:
      dockerfile: Dockerfile
    container_name: drupal
    ports:
      - "80:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  drupal-data:
# db-data:
